/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Dark theme (cinematic)
        void: 'var(--color-void)',
        pure: 'var(--color-pure)',
        graphite: 'var(--color-graphite)',
        steel: 'var(--color-steel)',
        fog: 'var(--color-fog)',
        ash: 'var(--color-ash)',
        violet: 'var(--color-violet)',
        amber: 'var(--color-amber)',
        green: 'var(--color-green)',
        glass: 'var(--surface-editor)',
        // Light theme (Air)
        sky: 'var(--color-sky)',
        action: 'var(--color-action)',
        midnight: 'var(--color-midnight)',
        cloud: 'var(--color-cloud)',
        charcoal: 'var(--color-charcoal)',
        haze: 'var(--color-haze)',
      },
      fontFamily: {
        display: ['"Playfair Display"', 'Georgia', 'serif'],
        mono: ['"Space Mono"', 'ui-monospace', 'monospace'],
        body: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        cursive: ['"Dancing Script"', 'cursive'],
        compressed: ['Oswald', 'Impact', 'sans-serif'],
      },
      fontSize: {
        caption: ['12px', { lineHeight: '1.5' }],
        xs: ['12px', { lineHeight: '1.4' }],
        sm: ['13px', { lineHeight: '1.4' }],
        base: ['14px', { lineHeight: '1.5' }],
        lg: ['16px', { lineHeight: '1.88' }],
        'heading-sm': ['20px', { lineHeight: '1.1' }],
        heading: ['32px', { lineHeight: '1.1' }],
        'heading-lg': ['56px', { lineHeight: '1' }],
        '4xl': ['2.25rem', { lineHeight: '0.95', letterSpacing: '-0.02em' }],
        '5xl': ['3rem', { lineHeight: '0.95', letterSpacing: '-0.02em' }],
        '6xl': ['3.75rem', { lineHeight: '0.95', letterSpacing: '-0.02em' }],
        display: ['259px', { lineHeight: '0.85' }],
      },
      borderRadius: {
        xs: '4px',
        sm: '5px',
        panel: '12px',
        pill: '500px',
        cards: '14px',
        links: '8px',
        images: '11px',
        inputs: '4px',
        buttons: '8px',
      },
      spacing: {
        '1': '4px',
        '1.5': '6px',
        '3': '12px',
        '3.5': '14px',
        '4': '16px',
        '4.5': '18px',
        '7': '28px',
      },
      keyframes: {
        'fade-rise': {
          from: { opacity: '0', transform: 'translateY(24px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'subtle-float': {
          '0%,100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-6px)' },
        },
        'pulse-glow': {
          '0%,100%': { opacity: '0.2' },
          '50%': { opacity: '0.6' },
        },
        'gradient-shift': {
          '0%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
          '100%': { backgroundPosition: '0% 50%' },
        },
      },
      animation: {
        'fade-rise': 'fade-rise 0.7s ease-out',
        'subtle-float': 'subtle-float 3s ease-in-out infinite',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        'gradient-shift': 'gradient-shift 6s ease infinite',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
